version: "3.1"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: "sales-system-mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: sales-system

  backend:
    image: leticiatakeshiro/sales-system-backend
    ports:
      - "3000:3000"
    container_name: "sales-system-backend"
    restart: always
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: docker
      DATABASE_NAME: sales-system
      DATABASE_PORT: 3306

  frontend:
    image: leticiatakeshiro/sales-system-frontend
    ports:
      - "80:80"
    container_name: "sales-system-frontend"
    restart: always
